language: ruby
rvm:
  - 1.9.3
  - 1.8.7
before_script:
 - sudo apt-get install postgresql-9.1-postgis

 - createuser -D -R -S osmer
 - createdb -O osmer osmerdb

 - psql -c "ALTER USER osmer PASSWORD 'qwerty'"
 - psql -d osmerdb -c "CREATE EXTENSION hstore"
 - psql -d osmerdb < /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql
 - psql -d osmerdb < /usr/share/postgresql/9.1/contrib/postgis-1.5/spatial_ref_sys.sql
 - psql -d osmerdb -c "GRANT ALL ON spatial_ref_sys TO osmer"
 - psql -d osmerdb -c "GRANT ALL ON geometry_columns TO osmer"
